#!/bin/sh
for file in \
            start.elf \
            start_cd.elf \
            start_db.elf \
            start_x.elf \
            fixup.dat \
            fixup_cd.dat \
            fixup_db.dat \
            fixup_x.dat \
            bootcode.bin \
            LICENCE.broadcom \
            ; do
    rm -f $file
    dpkg-divert --package rpikernelhack --remove --rename /boot/$file
    sync
done
#DEBHELPER#
