#!/bin/sh
if ! dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43430-sdio.bin"; then
    dpkg-divert --package raspberrypi-re4son-firmware --add --divert /lib/firmware/brcm/brcmfmac43430-sdio.bin.original --rename /lib/firmware/brcm/brcmfmac43430-sdio.bin
fi
if ! dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43430-sdio.txt"; then
    dpkg-divert --package raspberrypi-re4son-firmware --add --divert /lib/firmware/brcm/brcmfmac43430-sdio.txt.original --rename /lib/firmware/brcm/brcmfmac43430-sdio.txt
fi
if ! dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43455-sdio.bin"; then
    dpkg-divert --package raspberrypi-re4son-firmware --add --divert /lib/firmware/brcm/brcmfmac43455-sdio.bin.original --rename /lib/firmware/brcm/brcmfmac43455-sdio.bin
fi
if ! dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43455-sdio.clm_blob"; then
    dpkg-divert --package raspberrypi-re4son-firmware --add --divert /lib/firmware/brcm/brcmfmac43455-sdio.clm_blob.original --rename /lib/firmware/brcm/brcmfmac43455-sdio.clm_blob
fi
if ! dpkg-divert --list | grep -F "/lib/firmware/brcm/brcmfmac43455-sdio.txt"; then
    dpkg-divert --package raspberrypi-re4son-firmware --add --divert /lib/firmware/brcm/brcmfmac43455-sdio.txt.original --rename /lib/firmware/brcm/brcmfmac43455-sdio.txt
fi
#DEBHELPER#
